cadastros/urls.py
from django.contrib import admin
from django.urls import path
from .views import PrimeiraView, EditView, DeleteView, login

from django.conf.urls import include
from . import views
from cadastros.apis import *

urlpatterns = [

    path('primeira-view/',PrimeiraView, name='primeira-view'),
    path('edit-view/<int:pk>/',EditView, name='edit-view'),
    path('delete-view/<int:pk>/',DeleteView, name='delete-view'),


    path('',views.login,name='index'),
    path('index',views.login,name='index'),

    path('login', views.do_login, name='login'),

    path('api/', include([

        path('api-principal', PrincipalAPI.as_view(), name='api-principal'),
        path('api-post', PessoaPostAPI.as_view(), name='api-post'),
        path('api-delete', PessoaDeleteAPI.as_view(), name='api-delete'),


    ])),
    
]

proj/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastros.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, Permission, Group
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager



class UsuarioManager(BaseUserManager):
    def create_user(self, login, nome, email, password=None):

        user = self.model(
            login=login,
            nome=nome,
            email=email

        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, nome, email, password):

        user = self.create_user(
            login,
            nome,
            email

        )
        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user



class Usuario(AbstractBaseUser, PermissionsMixin):
    """Model definition for Usuario."""

    nome = models.CharField('Nome', max_length=80)
    login = models.CharField('Login', max_length=50, unique=True)
    password = models.CharField('Senha', max_length=128)
    email = models.EmailField('Email', max_length=254)

    # campos necessários pra o DJango
    last_login = models.DateTimeField(
        'Último login', blank=True, null=True, db_column='last_login')
    is_active = models.BooleanField('Ativo', default=True)
    is_admin = models.BooleanField('Ativo', default=False)
    is_staff = models.BooleanField('Staff', default=True)
    user_permissions = models.ManyToManyField(Permission, blank=True)
    groups = models.ManyToManyField(Group, blank=True)

    USERNAME_FIELD = 'login'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['nome','email']

    objects = UsuarioManager()


    def get_full_name(self):
        return self.Nome
    
   
    class Meta:
        """Meta definition for Usuario."""

        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        """Unicode representation of Usuario."""
        return self.Nome



# Create your models here.
PROFISSAO = (
        ('ENGENHEIRO', 'Engenheiro'),
        ('PROFESSOR', 'Professor'),
        ('ESTUDANTE', 'Estudante'),
    )



class Pessoa(models.Model):

    nome = models.CharField('Nome da Pessoa',max_length=150, null=True, blank=True )
    profissao = models.CharField('Profissão',max_length=150, choices=PROFISSAO, null=True)
    endereco = models.CharField('Endereço',max_length=150, null=True, blank=True)
    numero = models.IntegerField('Numero', null=True, blank=True)

    date = models.DateField('Data',null=True, blank=True)
    
    
    def __str__(self):
        return f'{self.nome}'+' - '+f'{self.numero}'
    

cadastros/forms.py
from django import forms
from .models import Pessoa


class PessoaForm(forms.ModelForm):

    

    class Meta:
        model = Pessoa
        fields = '__all__'


    widgets = {
        'date': forms.TextInput(attrs={'class':'form-control','type':'date'}),
    }
       

cadastros/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.views.generic.base import TemplateView, View
from .forms import PessoaForm
from django.contrib import messages
from .models import Pessoa
from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate, login as logon, logout




def login(request):
    return render(request,'login.html')



def do_login(request):
    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            logon(request, user)
            return redirect('primeira-view')
        else:
            messages.error(request,'Login ou Senha inválido!')
            return redirect('login')
    return render(request, 'login.html')



@login_required
def PrimeiraView(request):

    form = PessoaForm(request.POST or None)
    tipo_message = None
    pessoa = Pessoa.objects.filter().order_by('numero')
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Formulário Salvo com sucesso!')
            tipo_message = 'S'
        else:
            tipo_message = 'E'
            messages.error(request,'Erro ao salvar fomulario')

    context = {
        'form': form,
        'tipo_message': tipo_message,
        'pessoa': pessoa, 
       
    }

    return render(request,'cadastros/primeira-view.html', context)


def EditView(request,pk):

    obj = Pessoa.objects.get(pk=pk)
    form = PessoaForm(request.POST or None, instance=obj)


    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Formulário Editado com sucesso!')
            return redirect('primeira-view')
            
    context = {
       'pk': pk, 
       'form': form,
       
    }

    return render(request,'cadastros/edit_view.html', context)




def DeleteView(request,pk):

    obj = Pessoa.objects.get(pk=pk)
    obj.delete()
    messages.success(request,'Formulário Deletado com sucesso!')
    return redirect('primeira-view')
            









def Teste(request):


    context = {
       
       
    }

    return render(request,'cadastros/teste.html', context)









# class TESTE(View):



#     def get_template_names(self):
    
#     def post(self):

cadastros/templates/cadastros/edit_view.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% if messages %}

    
        {% for message in messages %}


            
            <div class="alert alert-{% if tipo_message == 'S' %}{{ message.tags }}{% endif %}{% if tipo_message == 'E' %}danger{% endif %} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×
                </button>
                {{ message }}
            </div>
       
    


        {% endfor %}
    {% endif %}

    

<div class="col-md-6">
    

  
  
  
  
  <form method="POST">
        <div class="form-group">
          
          {{ pk }}
          {% csrf_token %}
            
          {{ form }}
        </div>


   
        <button type="submit" class="btn btn-primary">Edit</button>
      </form>
    </div>





    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

cadastros/templates/cadastros/primeira-view.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% if messages %}

    
        {% for message in messages %}


            
            <div class="alert alert-{% if tipo_message == 'S' %}{{ message.tags }}{% endif %}{% if tipo_message == 'E' %}danger{% endif %} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×
                </button>
                {{ message }}
            </div>
       
    


        {% endfor %}
    {% endif %}

    

<div class="col-md-6">
    

  
  
  
  
  <form method="POST">
        <div class="form-group">
          
          
          {% csrf_token %}
            
          {{ form }}
        </div>


   
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>


    <div>

      <table style="width: 100%; border: 2px;">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Endereco</th>
            <th>Profissao</th>
            <th>Numero</th>
            <th>Data</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for x in pessoa %}
          <tr>
              <td>{{ x.pk }}</td>
              <td>{{ x.nome }}</td>
              <td>{{ x.endereco }}</td>
              <td>{{ x.profissao|default:'Sem registros' }}</td>
              <td>{{ x.numero }}</td>
              <td>{{ x.date }}</td>
              <td>
                <a href="{% url 'edit-view' x.pk %}">
                  <button type="button" class="btn btn-info">Editar</button>
                </a>

                <a href="{% url 'delete-view' x.pk %}">
                  <button type="button" class="btn btn-danger">Deletar</button>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

cadastros/templates/cadastros/teste.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   
<div class="col-md-6">



  
  <form method="POST">
    <div class="form-group">
      

<tr><th><label for="id_nome">Nome da Pessoa:</label></th><td><input type="text" name="nome" maxlength="150" id="id_nome"></td></tr>

<tr><th><label for="id_endereco">Endereço:</label></th><td><input type="text" name="endereco" maxlength="150" id="id_endereco"></td></tr>
<tr><th><label for="id_numero">Numero:</label></th><td><input type="number" name="numero" id="id_numero"></td></tr>
<tr><th><label for="id_date">Data:</label></th><td><input type="text" name="date" id="id_date"></td></tr>




</div>


   
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/login.html
<!DOCTYPE html>


<html>

<head>


<meta charset="UTF-8"/>
<title>Aula Tópicos</title>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">



<link rel="stylesheet" type="text/css" href="./login.css">




</head>
<body>

    <div class="container">
    	<div class="row">
            {% if messages %}

    
            {% for message in messages %}
    
    
                
                <div class="alert alert-{% if tipo_message == 'S' %}{{ message.tags }}{% endif %}{% if tipo_message == 'E' %}danger{% endif %} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        ×
                    </button>
                    {{ message }}
                </div>
           
        
    
    
            {% endfor %}
        {% endif %}

			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="{% url 'login' %}" method="POST" role="form" style="display: block;">
                                    {% csrf_token %}
                                    <div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="https://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
								<form id="register-form" action="https://phpoll.com/register/process" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


    <script type="text/javascript" src="./login.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


</body>
</html>